---

- name: PDNS Recursor Master
  hosts: all
  vars_files:
    - ../resources/vars/pdns-rec-common.yml
    - ../resources/vars/pdns-rec-repo-master.yml
  roles:
    - { role: powerdns.pdns_recursor }
